log4j:WARN No appenders could be found for logger (org.openspaces.core.space.UrlSpaceFactoryBean).
log4j:WARN Please initialize the log4j system properly.
2015-04-18 18:51:26,332  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred during query, discarding reggie [com.sun.jini.reggie.RegistrarProxy[registrar=0575c7b1-5db8-4b54-abd0-ba5674d30afc DynamicSmartStub [ImplObjClass: com.sun.jini.reggie.GigaRegistrar, ConnectionURL: NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar], MaxConnPool: 1024 ]]]; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:51:30,987  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred during query, discarding reggie [com.sun.jini.reggie.RegistrarProxy[registrar=0575c7b1-5db8-4b54-abd0-ba5674d30afc DynamicSmartStub [ImplObjClass: com.sun.jini.reggie.GigaRegistrar, ConnectionURL: NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar], MaxConnPool: 1024 ]]]; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:51:31,231  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:51:36,182  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:51:41,181  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:51:43,590  INFO [net.jini.discovery.LookupDiscovery] - exception occurred during unicast discovery to kafka.local:4174 with constraints InvocationConstraints[reqs: {}, prefs: {}]; Caused by: java.net.ConnectException: Connection refused
2015-04-18 18:51:43,593  INFO [net.jini.discovery.LookupDiscovery] - exception occurred during unicast discovery to kafka.local:4174 with constraints InvocationConstraints[reqs: {}, prefs: {}]; Caused by: java.net.ConnectException: Connection refused
2015-04-18 18:51:46,181  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:51:51,182  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:51:56,183  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
2015-04-18 18:52:01,182  INFO [net.jini.lookup.ServiceDiscoveryManager] - Exception occurred while attempting to register with the lookup service event mechanism; Caused by: java.rmi.ConnectException: Connect Failed to [NIO://kafka.local:53309/pid[35458]/1429346479421803232_2_639148318494860921_details[class com.sun.jini.reggie.GigaRegistrar]]; nested exception is: 
	java.net.ConnectException: Connection refused
